"""file_data_table_added

Revision ID: 2eac572792da
Revises: 5cb253cd5f4f
Create Date: 2025-10-09 12:32:55.209850

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "2eac572792da"
down_revision: Union[str, Sequence[str], None] = "5cb253cd5f4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filedata",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("file_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("file_index", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_filedata_file_index"), "filedata", ["file_index"], unique=False
    )
    op.create_index(
        op.f("ix_filedata_file_name"), "filedata", ["file_name"], unique=False
    )
    op.create_index(
        op.f("ix_filedata_file_url"), "filedata", ["file_url"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_filedata_file_url"), table_name="filedata")
    op.drop_index(op.f("ix_filedata_file_name"), table_name="filedata")
    op.drop_index(op.f("ix_filedata_file_index"), table_name="filedata")
    op.drop_table("filedata")
    # ### end Alembic commands ###
