"""account number not unique

Revision ID: 5cb253cd5f4f
Revises: d6bce694641a
Create Date: 2025-10-03 19:39:15.405654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5cb253cd5f4f'
down_revision: Union[str, Sequence[str], None] = 'd6bce694641a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bankdetails_account_number'), table_name='bankdetails')
    op.create_index(op.f('ix_bankdetails_account_number'), 'bankdetails', ['account_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bankdetails_account_number'), table_name='bankdetails')
    op.create_index(op.f('ix_bankdetails_account_number'), 'bankdetails', ['account_number'], unique=True)
    # ### end Alembic commands ###
