"""removed two fileds

Revision ID: 73f51e6f2112
Revises: 78ce0dc4e6f3
Create Date: 2025-10-03 16:40:42.631789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '73f51e6f2112'
down_revision: Union[str, Sequence[str], None] = '78ce0dc4e6f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_c_gst'), table_name='payment')
    op.drop_index(op.f('ix_payment_s_gst'), table_name='payment')
    op.drop_column('payment', 'c_gst')
    op.drop_column('payment', 's_gst')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('s_gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('payment', sa.Column('c_gst', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_payment_s_gst'), 'payment', ['s_gst'], unique=False)
    op.create_index(op.f('ix_payment_c_gst'), 'payment', ['c_gst'], unique=False)
    # ### end Alembic commands ###
