"""add number

Revision ID: 78ce0dc4e6f3
Revises: b1212bb61c4b
Create Date: 2025-10-03 16:38:18.394594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "78ce0dc4e6f3"
down_revision: Union[str, Sequence[str], None] = "b1212bb61c4b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "customer",
        sa.Column("number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.create_index(op.f("ix_customer_number"), "customer", ["number"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customer_number"), table_name="customer")
    op.drop_column("customer", "number")
    # ### end Alembic commands ###
