"""added c_gst and s_gst

Revision ID: 80fd556be4de
Revises: 73f51e6f2112
Create Date: 2025-10-03 16:43:44.076974

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "80fd556be4de"
down_revision: Union[str, Sequence[str], None] = "73f51e6f2112"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_customer_number"), table_name="customer")
    op.drop_column("customer", "number")
    op.add_column("payment", sa.Column("s_gst", sa.Float(), nullable=True))
    op.add_column("payment", sa.Column("c_gst", sa.Float(), nullable=True))
    op.create_index(op.f("ix_payment_c_gst"), "payment", ["c_gst"], unique=False)
    op.create_index(op.f("ix_payment_s_gst"), "payment", ["s_gst"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payment_s_gst"), table_name="payment")
    op.drop_index(op.f("ix_payment_c_gst"), table_name="payment")
    op.drop_column("payment", "c_gst")
    op.drop_column("payment", "s_gst")
    op.add_column(
        "customer",
        sa.Column("number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.create_index(op.f("ix_customer_number"), "customer", ["number"], unique=False)
    # ### end Alembic commands ###
