"""changed the database

Revision ID: b5553950a9bb
Revises: da4e3ad67bee
Create Date: 2025-10-03 15:48:21.010044

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "b5553950a9bb"
down_revision: Union[str, Sequence[str], None] = "da4e3ad67bee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "phone_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("phone_number", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
