"""invoice must be unique

Revision ID: d6bce694641a
Revises: b8565200985d
Create Date: 2025-10-03 19:08:39.729688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bce694641a'
down_revision: Union[str, Sequence[str], None] = 'b8565200985d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'invoice_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('invoice', 'invoice_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
