"""added the c_gst

Revision ID: de587e3cc952
Revises: b5553950a9bb
Create Date: 2025-10-03 16:27:20.875765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de587e3cc952'
down_revision: Union[str, Sequence[str], None] = 'b5553950a9bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment', sa.Column('c_gst', sa.Float(), nullable=True))
    op.create_index(op.f('ix_payment_c_gst'), 'payment', ['c_gst'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_c_gst'), table_name='payment')
    op.drop_column('payment', 'c_gst')
    # ### end Alembic commands ###
